server:
  port: 0

spring:
  application:
    name: app-service
  cloud:
    config:
      name: tradeinsurance
  config:
    import: configserver:http://127.0.0.1:8888

#tradeinsurance:
#  profile: dev

management:
  endpoints:
    web:
      exposure:
        include: info, refresh, health, beans
  endpoint:
    info:
      enabled: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


logging:
  level:
    web: debug