server:
  port: 8000

#system:
#  properties:
#    io.netty.dns.noNative: true
spring:
  application:
    name: apigateway-service
  cloud:
    config:
      name: tradeinsurance
  config:
    import: configserver:http://127.0.0.1:8888


management:
  endpoints:
    web:
      exposure:
        include: gateway, info, refresh, health, beans, httptrace
  endpoint:
    info:
      enabled: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

  application:
    name: apigateway-service

  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      # CustomFilter : 라우터별로 각각 설정 필요 (vs GlobalFilter)
      routes:
        - id: app-service
          uri: lb://app-service
          predicates:
            - Path=/app-service/**
            - Method=GET,POST
          filters:
#            - RemoveRequestHeader=Cookie
            - RewritePath=/app-service/(?<segment>.*), /$\{segment}
        - id: app-service-actuator
          uri: lb://app-service
          predicates:
            - Path=/app-service/actuator/**
            - Method=GET,POST
          filters:
#            - RemoveRequestHeader=Cookie
            - RewritePath=/app-service/(?<segment>.*), /$\{segment}
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/review-service/**
          filters:
#            - RemoveRequestHeader=Cookie
            - RewritePath=/review-service/(?<segment>.*), /$\{segment}


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    io.netty: DEBUG
