server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
#        native:
#          search-locations: file:///Users/mooni/development/trade-insurance-system-settings
        git:
          uri: file:///Users/mooni/development/trade-insurance-system-settings
          default-label: main

logging:
  level:
    web: debug
