server:
  port: 8888

spring:
  application:
    name: config-service
#  profiles:
#    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/mooni/development/trade-insurance-system-settings
        git:
#          uri:
          uri: https://github.com/mooni9375/trade-insurance-system-config
          default-label: main

logging:
  level:
    web: debug
