server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  application:
    name: apigateway-service

spring:
  application:
    name: apigateway-service
  config:
    import: configserver:http://127.0.0.1:8888
  profiles:
    active: dev
  cloud:
    config:
      name: tradeinsurance-dev
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      # CustomFilter : 라우터별로 각각 설정 필요 (vs GlobalFilter)
      routes:
        - id: app-service
          uri: lb://APP-SERVICE
          predicates:
            - Path=/app-service/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/app-service/(?<segment>.*), /$\{segment}
        - id: app-service
          uri: lb://APP-SERVICE
          predicates:
            - Path=/app-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/app-service/(?<segment>.*), /$\{segment}
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/review-service/(?<segment>.*), /$\{segment}




management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
    health:
      show-details: always






logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    io.netty: DEBUG
